FROM node:16.17.1-alpine3.15

WORKDIR /nursery_front

COPY package.json /nursery_front
COPY yarn.lock /nursery_front

RUN yarn install --frozen-lockfile --production=false

COPY . /nursery_front

ENV PORT 3000
EXPOSE 3000