"""update PlanterOutput column ouput: Integer -> BigInteger

Revision ID: 03bfdc1bb312
Revises: 92d0e0933a0d
Create Date: 2023-08-24 18:18:02.303648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03bfdc1bb312'
down_revision: Union[str, None] = '92d0e0933a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
