"""regenerate planter model

Revision ID: 0f14d559bae9
Revises: 2e740a665308
Create Date: 2023-08-23 21:22:40.969029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f14d559bae9"
down_revision: Union[str, None] = "2e740a665308"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generatzed by Alembic - please adjust! ###
    op.create_table(
        "planters",
        sa.Column("farm_house_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("serial_number", sa.String(length=255), nullable=True),
        sa.Column("is_register", sa.Boolean(), nullable=True),
        sa.Column("register_date", sa.DateTime(), nullable=True),
        sa.Column("is_del", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["farm_house_id"],
            ["farm_houses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_planters_id"), "planters", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_planters_id"), table_name="planters")
    op.drop_table("planters")
    # ### end Alembic commands ###
