"""regenerate PlanterWork table

Revision ID: 11eb52d923a7
Revises: 40ceb8a2d76a
Create Date: 2023-08-24 00:37:40.321157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11eb52d923a7'
down_revision: Union[str, None] = '40ceb8a2d76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planter_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planter_id', sa.Integer(), nullable=True),
    sa.Column('planter_tray_id', sa.Integer(), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.Column('crop_kind', sa.String(length=255), nullable=True),
    sa.Column('sowing_date', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('order_quantity', sa.Integer(), nullable=True),
    sa.Column('seed_quantity', sa.Integer(), nullable=True),
    sa.Column('operating_time', sa.Integer(), nullable=True),
    sa.Column('is_del', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crops.id'], ),
    sa.ForeignKeyConstraint(['planter_id'], ['planters.id'], ),
    sa.ForeignKeyConstraint(['planter_tray_id'], ['planter_trays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planter_works_id'), 'planter_works', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planter_works_id'), table_name='planter_works')
    op.drop_table('planter_works')
    # ### end Alembic commands ###
