"""edit table PlanterWorkStatus

Revision ID: 14e48874decf
Revises: d49aa15b1a96
Create Date: 2023-08-24 00:48:29.143223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e48874decf'
down_revision: Union[str, None] = 'd49aa15b1a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
