"""update crop model : add name column

Revision ID: 2846f09a7182
Revises: 0f14d559bae9
Create Date: 2023-08-23 22:45:52.398030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2846f09a7182'
down_revision: Union[str, None] = '0f14d559bae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crops', sa.Column('name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_crops_name'), 'crops', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crops_name'), table_name='crops')
    op.drop_column('crops', 'name')
    # ### end Alembic commands ###
