"""Planter change column name moya -> farm_house_id

Revision ID: 39ea9c46dc1a
Revises: 10c0681451c5
Create Date: 2023-08-22 22:39:14.320434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ea9c46dc1a'
down_revision: Union[str, None] = '10c0681451c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planters', sa.Column('farm_house_id', sa.Integer(), nullable=True))
    op.drop_constraint('planters_moya_fkey', 'planters', type_='foreignkey')
    op.create_foreign_key(None, 'planters', 'farm_houses', ['farm_house_id'], ['id'])
    op.drop_column('planters', 'moya')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planters', sa.Column('moya', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'planters', type_='foreignkey')
    op.create_foreign_key('planters_moya_fkey', 'planters', 'farm_houses', ['moya'], ['id'])
    op.drop_column('planters', 'farm_house_id')
    # ### end Alembic commands ###
