"""regenerate PlanterStatus table

Revision ID: 40ceb8a2d76a
Revises: e41c72436569
Create Date: 2023-08-24 00:32:30.790480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40ceb8a2d76a'
down_revision: Union[str, None] = 'e41c72436569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planter_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planter_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.Column('is_del', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['planter_id'], ['planters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planter_status_id'), 'planter_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planter_status_id'), table_name='planter_status')
    op.drop_table('planter_status')
    # ### end Alembic commands ###
