"""update User table: login_id 칼럼 remove index, add nullable=True

Revision ID: 5d3b8c94912a
Revises: 1e56efb59c34
Create Date: 2023-09-25 20:11:30.721917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d3b8c94912a'
down_revision: Union[str, None] = '1e56efb59c34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_login_id', table_name='users')
    op.create_unique_constraint(None, 'users', ['login_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_login_id', 'users', ['login_id'], unique=False)
    # ### end Alembic commands ###
