"""update PlanterStatus, PlanterWork, PlanterOutput

Revision ID: 675832903055
Revises: 6f436f9ac9d7
Create Date: 2023-09-06 19:34:50.371553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '675832903055'
down_revision: Union[str, None] = '6f436f9ac9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planter_outputs', sa.Column('start_count', sa.Integer(), nullable=True))
    op.add_column('planter_outputs', sa.Column('end_count', sa.Integer(), nullable=True))
    op.add_column('planter_status', sa.Column('operating_time', sa.BigInteger(), nullable=True))
    op.drop_column('planter_works', 'operating_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planter_works', sa.Column('operating_time', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('planter_status', 'operating_time')
    op.drop_column('planter_outputs', 'end_count')
    op.drop_column('planter_outputs', 'start_count')
    # ### end Alembic commands ###
