"""add is_top_admin column in AdminUserInfo table

Revision ID: 7410003237aa
Revises: 1cda1d2b95dc
Create Date: 2023-09-08 16:00:40.994865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7410003237aa'
down_revision: Union[str, None] = '1cda1d2b95dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user_infos', sa.Column('is_top_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_user_infos', 'is_top_admin')
    # ### end Alembic commands ###
