"""add FarmHouse Column farm_house_id, producer_name

Revision ID: 84aca3a69fae
Revises: 8e05a7ea9002
Create Date: 2023-08-29 19:33:49.521993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84aca3a69fae'
down_revision: Union[str, None] = '8e05a7ea9002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm_houses', sa.Column('farm_house_id', sa.String(length=20), nullable=True))
    op.add_column('farm_houses', sa.Column('producer_name', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_farm_houses_farm_house_id'), 'farm_houses', ['farm_house_id'], unique=True)
    op.create_index(op.f('ix_farm_houses_producer_name'), 'farm_houses', ['producer_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farm_houses_producer_name'), table_name='farm_houses')
    op.drop_index(op.f('ix_farm_houses_farm_house_id'), table_name='farm_houses')
    op.drop_column('farm_houses', 'producer_name')
    op.drop_column('farm_houses', 'farm_house_id')
    # ### end Alembic commands ###
