"""create table PlanterOutput

Revision ID: 92d0e0933a0d
Revises: 14e48874decf
Create Date: 2023-08-24 00:57:58.209198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d0e0933a0d'
down_revision: Union[str, None] = '14e48874decf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planter_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planter_work_id', sa.Integer(), nullable=True),
    sa.Column('output', sa.Integer(), nullable=True),
    sa.Column('is_del', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['planter_work_id'], ['planter_works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planter_outputs_id'), 'planter_outputs', ['id'], unique=False)
    op.create_index(op.f('ix_planter_works_crop_kind'), 'planter_works', ['crop_kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planter_works_crop_kind'), table_name='planter_works')
    op.drop_index(op.f('ix_planter_outputs_id'), table_name='planter_outputs')
    op.drop_table('planter_outputs')
    # ### end Alembic commands ###
