"""update PlanterWork column order_quantity, seed_quantity, operating_time

Revision ID: 9d2afeb0436f
Revises: b13a69551729
Create Date: 2023-08-24 18:28:19.817892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d2afeb0436f"
down_revision: Union[str, None] = "b13a69551729"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "planter_works",
        "order_quantity",
        existing_type=sa.Integer(),
        type_=sa.BigInteger(),
    )
    op.alter_column(
        "planter_works",
        "seed_quantity",
        existing_type=sa.Integer(),
        type_=sa.BigInteger(),
    )
    op.alter_column(
        "planter_works",
        "operating_time",
        existing_type=sa.Integer(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "planter_works",
        "order_quantity",
        existing_type=sa.BigInteger(),
        type_=sa.Integer(),
    )
    op.alter_column(
        "planter_works",
        "seed_quantity",
        existing_type=sa.BigInteger(),
        type_=sa.Integer(),
    )
    op.alter_column(
        "planter_works",
        "operating_time",
        existing_type=sa.BigInteger(),
        type_=sa.Integer(),
        nullable=False,
    )
    # ### end Alembic commands ###
