"""drop AdminUserInfo table

Revision ID: ada14327bdcc
Revises: c9da447e8d70
Create Date: 2023-09-08 14:48:44.159792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ada14327bdcc'
down_revision: Union[str, None] = 'c9da447e8d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_user_infos_company', table_name='admin_user_infos')
    op.drop_index('ix_admin_user_infos_id', table_name='admin_user_infos')
    op.drop_table('admin_user_infos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user_infos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('is_del', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='admin_user_infos_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='admin_user_infos_pkey')
    )
    op.create_index('ix_admin_user_infos_id', 'admin_user_infos', ['id'], unique=False)
    op.create_index('ix_admin_user_infos_company', 'admin_user_infos', ['company'], unique=False)
    # ### end Alembic commands ###
