"""add PlanterOutput column output

Revision ID: b13a69551729
Revises: 274085eaeab3
Create Date: 2023-08-24 18:22:21.210066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13a69551729'
down_revision: Union[str, None] = '274085eaeab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planter_outputs', sa.Column('output', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planter_outputs', 'output')
    # ### end Alembic commands ###
