"""Add crop_code column in Crop Table

Revision ID: c5f6ecf842cf
Revises: 5d3b8c94912a
Create Date: 2023-10-25 13:33:56.399649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f6ecf842cf'
down_revision: Union[str, None] = '5d3b8c94912a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crops', sa.Column('crop_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crops', 'crop_code')
    # ### end Alembic commands ###
