"""create base model

Revision ID: c943e67150d8
Revises: 
Create Date: 2023-08-23 18:09:46.245762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c943e67150d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('farm_houses', sa.Column('is_del', sa.Boolean(), nullable=True))
    op.add_column('farm_houses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('farm_houses', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('planters', sa.Column('is_del', sa.Boolean(), nullable=True))
    op.add_column('planters', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('planters', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_del', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_del')
    op.drop_column('planters', 'updated_at')
    op.drop_column('planters', 'created_at')
    op.drop_column('planters', 'is_del')
    op.drop_column('farm_houses', 'updated_at')
    op.drop_column('farm_houses', 'created_at')
    op.drop_column('farm_houses', 'is_del')
    # ### end Alembic commands ###
