"""create AdminUserInfo table

Revision ID: c9da447e8d70
Revises: d13edd416d7f
Create Date: 2023-09-08 14:34:56.933706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9da447e8d70'
down_revision: Union[str, None] = 'd13edd416d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=30), nullable=True),
    sa.Column('department', sa.String(length=30), nullable=True),
    sa.Column('position', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_del', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_user_infos_company'), 'admin_user_infos', ['company'], unique=False)
    op.create_index(op.f('ix_admin_user_infos_id'), 'admin_user_infos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_user_infos_id'), table_name='admin_user_infos')
    op.drop_index(op.f('ix_admin_user_infos_company'), table_name='admin_user_infos')
    op.drop_table('admin_user_infos')
    # ### end Alembic commands ###
