"""update PlanterWork column : add is_shipment_completed


Revision ID: d13edd416d7f
Revises: 675832903055
Create Date: 2023-09-07 22:03:31.038903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13edd416d7f'
down_revision: Union[str, None] = '675832903055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planter_works', sa.Column('is_shipment_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planter_works', 'is_shipment_completed')
    # ### end Alembic commands ###
