"""update Farmhouse table nursery_number column

Revision ID: d8b81bcec7aa
Revises: 7410003237aa
Create Date: 2023-09-25 20:06:08.725745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b81bcec7aa'
down_revision: Union[str, None] = '7410003237aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_farm_houses_nursery_number', table_name='farm_houses')
    op.create_unique_constraint(None, 'farm_houses', ['nursery_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'farm_houses', type_='unique')
    op.create_index('ix_farm_houses_nursery_number', 'farm_houses', ['nursery_number'], unique=False)
    # ### end Alembic commands ###
