"""add Planter Column qrcode

Revision ID: fea6697c073f
Revises: 84aca3a69fae
Create Date: 2023-08-29 19:42:17.815356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea6697c073f'
down_revision: Union[str, None] = '84aca3a69fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planters', sa.Column('qrcode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planters', 'qrcode')
    # ### end Alembic commands ###
